 CREATE TABLE USERS(
	ID_USER SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	USERNAME VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	PHONE VARCHAR NOT NULL,
	STATUS INTEGER NOT NULL,
	IMAGE VARCHAR,
	ROL INTEGER NOT NULL,
	DEPARTAMENT VARCHAR,
	CITY VARCHAR,
	STREET VARCHAR,
	NEIGHBORHOOD VARCHAR
 );
 
 CREATE TABLE STORE(
	ID_USER SERIAL PRIMARY KEY NOT NULL,
	RUT VACHAR NOT NULL,
	SOCIAL_REASON VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
 );
 
 CREATE TABLE ADMINS(
	ID_USER SERIAL PRIMARY KEY NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL
 );
 
 CREATE TABLE PRODUCT(
	ID_PRODUCT VARCHAR NOT NULL,
	ID_USER SERIAL NOT NULL,
	PRICE INTEGER NOT NULL,
	F_CURRENCY NOT NULL,
	DESCRIPTION	VARCHAR NOT NULL,
	CATEGORY SERIAL NOT NULL,
	SUBCATEGORY SERIAL NOT NULL,
	NAME VARCHAR NOT NULL,
	STOCK INTEGER,
	WARRANTY VARCHAR,
	STATUS INTEGER,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY(SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );
 
 CREATE TABLE PRODUCT_COMMENT(
	ID_COMMENT SERIAL PRIMARY KEY NOT NULL,
	ID_USER	SERIAL NOT NULL,
	COMMENT_TEXT VARCHAR NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	COMMENT_DATE TIMESTAMP,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE PRODUCT_RATING(
	ID_USER	SERIAL PRIMARY KEY NOT NULL,
	ID_PRODUCT VARCHAR PRIMARY KEY NOT NULL,
	TITLE VARCHAR,
	RATING_INTEGER INTEGER,
	DESCRIPTION	VARCHAR,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE FAVOURITE(
	ID_USER	SERIAL PRIMARY KEY NOT NULL,
	ID_PRODUCT	VARCHAR PRIMARY KEY NOT NULL,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE HISTORY(
	ID_USER	SERIAL PRIMARY KEY NOT NULL,
	ID_PRODUCT	VARCHAR PRIMARY KEY NOT NULL,
	DATE_OF_VISIT TIMESTAMP NOT NULL,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE COMMENT_ANSWER(
	ID_ANSWER SERIAL PRIMARY KEY NOT NULL,
	ID_USER	SERIAL,
	ANSWER_TEXT	VARCHAR,
	ID_PRODUCT VARCHAR,
	ID_COMMENT VARCHAR,
	ANSWER_DATE TIMESTAMP,
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
	FOREIGN KEY(ID_COMMENT) REFERENCES PRODUCT_COMMENT(ID_COMMENT)
 );
 
 CREATE TABLE SELL(
	ID_SELL SERIAL PRIMARY KEY NOT NULL,
	ID_SELLER_USER SERIAL NOT NULL,
	ID_BUYER_USER SERIAL NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	SELL_DATE DATE,
	
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
	FOREIGN KEY(ID_SELLER_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY(ID_BUYER_USER) REFERENCES USER(ID_USER),
);
 
 CREATE TABLE CATEGORY(
	ID_CATEGORY SERIAL PRIMARY KEY NOT NULL
 );
 
 CREATE TABLE CATEGORY_ES(
	ID_CATEGORY SERIAL PRIMARY KEY NOT NULL,
	MAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
 );
 
 CREATE TABLE CATEGORY_EN(
	ID_CATEGORY SERIAL PRIMARY KEY NOT NULL,
	MAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
 );
 
 CREATE TABLE SUBCATEGORY(
	ID_SUBCATEGORY SERIAL PRIMARY KEY NOT NULL
 );
 
 CREATE TABLE SUBCATEGORY_ES(
	ID_SUBCATEGORY SERIAL PRIMARY KEY NOT NULL,
	ID_CATEGORY SERIAL PRIMARY LEY NOT NULL,
	MAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );
 
  CREATE TABLE SUBCATEGORY_EN(
	ID_SUBCATEGORY SERIAL PRIMARY KEY NOT NULL,
	ID_CATEGORY SERIAL PRIMARY LEY NOT NULL,
	MAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );
 
 CREATE TABLE CATEGORY_BRAND(
	ID_CATEGORY SERIAL PRIMARY KEY NOT NULL,
	BRAND VARCHAR,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
 );
 
  CREATE TABLE SUBCATEGORY_BRAND(
	ID_SUBCATEGORY SERIAL PRIMARY KEY NOT NULL,
	BRAND VARCHAR,
	
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );
 
 CREATE TABLE CATEGORY_FILTER(
	ID_CATEGORY SERIAL NOT NULL PRIMARY KEY,
	ID_FILTER SERIAL NOT NULL PRIMARY KEY,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
 );
 
 CREATE TABLE SUBCATEGORY_FILTER(
	ID_SUBCATEGORY SERIAL NOT NULL PRIMARY KEY,
	ID_FILTER SERIAL NOT NULL PRIMARY KEY,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES SUBCATEGORY(ID_CATEGORY),
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
 );
 
 CREATE TABLE FILTER(
	ID_FILTER SERIAL PRIMARY KEY NOT NULL,
	FILTER_NAME VARCHAR,
	FILTER_TYPE VARCHAR
 );
 
 CREATE TABLE FILTER_ES(
	ID_FILTER SERIAL PRIMARY KEY NOT NULL,
	FILTER_NAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
 );
 
 CREATE TABLE FILTER_EN(
	ID_FILTER SERIAL PRIMARY KEY NOT NULL,
	FILTER_NAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
 );
 
 CREATE TABLE NOTIFICATION_GENERIC(
	ID_NOTIFICATION SERIAL PRIMARY KEY NOT NULL,
	MESSAGE VARCHAR NOT NULL,
	ID_USER SERIAL NOT NULL,
	NOTIFICATION_DATE TIMESTAMP NOT NULL
	
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
);

 CREATE TABLE NOTIFICATION_COMMENT(
	ID_NOTIFICATION SERIAL PRIMARY KEY NOT NULL,
	ID_COMMENT SERIAL NOT NULL,
	
	FOREIGN KEY(ID_COMMENT) REFERENCES PRODUCT_COMMENT(ID_COMMENT)
);

 CREATE TABLE NOTIFICATION_ANSWER(
	ID_NOTIFICATION SERIAL PRIMARY KEY NOT NULL,
	ID_ANSWER SERIAL NOT NULL,
	
	FOREIGN KEY(ID_ANSWER) REFERENCES COMMENT_ANSWER(ID_ANSWER)
);
