-- Filtros genéricos

-- Precio 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Precio','NUMERIC_RANGE');

-- Nuevo o usado 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Nuevo o usado','OPTIONS_LIST');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Nuevo' FROM FILTER WHERE FILTER_NAME = 'Nuevo o usado');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Usado' FROM FILTER WHERE FILTER_NAME = 'Nuevo o usado');

-- Ubicación del vendedor 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Ubicación del vendedor','SELECTIONABLE_LIST');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Montevideo' FROM FILTER WHERE FILTER_NAME = 'Ubicación del vendedor');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Canelones' FROM FILTER WHERE FILTER_NAME = 'Ubicación del vendedor');

-- Tiendas oficiales 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Tiendas oficiales','BOOLEAN');


update filter set id_category = 0, id_subcategory = 0 where is_generic = 1;
UPDATE FILTER SET TABLE_NAME = 'PRODUCT' WHERE IS_GENERIC = 1;

UPDATE FILTER SET COLUMN_NAME = 'NewOrUsed' WHERE ID_FILTER = 2;
UPDATE FILTER SET COLUMN_NAME = 'Ubication' WHERE ID_FILTER = 3;
UPDATE FILTER SET COLUMN_NAME = 'OfficialStore' WHERE ID_FILTER = 4;
UPDATE FILTER SET COLUMN_NAME = 'Price' WHERE ID_FILTER = 1;
 