-- Filtros genéricos

-- Precio 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Precio','NUMERIC_RANGE');

-- Nuevo o usado 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Nuevo o usado','OPTIONS_LIST');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Nuevo' FROM FILTER WHERE FILTER_NAME = 'Nuevo o usado');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Usado' FROM FILTER WHERE FILTER_NAME = 'Nuevo o usado');

-- Ubicación del vendedor 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Ubicación del vendedor','SELECTIONABLE_LIST');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Montevideo' FROM FILTER WHERE FILTER_NAME = 'Ubicación del vendedor');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Canelones' FROM FILTER WHERE FILTER_NAME = 'Ubicación del vendedor');

-- Tiendas oficiales 
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE)
VALUES(1, 'Tiendas oficiales','BOOLEAN');




 