-- Filtros genéricos

-- Precio 
INSERT INTO FILTER(IS_GENERIC, FILTER_TYPE)
VALUES(1, 'NUMERIC_RANGE');

INSERT INTO FILTER_ES(ID_FILTER, FILTER_NAME)
(SELECT MAX(ID_FILTER), 'Precio' FROM FILTER);

INSERT INTO FILTER_EN(ID_FILTER, FILTER_NAME)
(SELECT MAX(ID_FILTER), 'Price' FROM FILTER);