-- Subcategorías de --> Vehículos ------------------------------------------------------------------------------------------------------------------------------------------------

-- Autos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Vehículos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Autos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cars' FROM SUBCATEGORY);

-- Camionetas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Vehículos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Camionetas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Vans' FROM SUBCATEGORY);

-- Camiones y vehículos comerciales
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Vehículos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Camiones y vehículos comerciales' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Trucks and commercial vehicles' FROM SUBCATEGORY);

-- Motos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Vehículos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Motos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Motorcycles' FROM SUBCATEGORY);

-- Subcategorías de --> Inmuebles y propiedades ------------------------------------------------------------------------------------------------------------------------------------------------

-- Casas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Inmuebles y propiedades');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Casas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Houses' FROM SUBCATEGORY);

-- Apartamentos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Inmuebles y propiedades');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Apartamentos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Apartments' FROM SUBCATEGORY);

-- Depósitos y garages
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Inmuebles y propiedades');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Depósitos y garages' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Warehouses and garages' FROM SUBCATEGORY);

-- Oficinas y locales comerciales
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Inmuebles y propiedades');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Oficinas y locales comerciales' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Offices and commercial premises' FROM SUBCATEGORY);

-- Terrenos y campos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Inmuebles y propiedades');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Terrenos y campos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Lands and fields' FROM SUBCATEGORY);

-- Subcategorías de --> Electrónica, video y audio ------------------------------------------------------------------------------------------------------------------------------------------------

-- TV's
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'TVs' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'TVs' FROM SUBCATEGORY);

-- Equipos de audio
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Equipos de audio' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Audio equipment' FROM SUBCATEGORY);

-- Cámaras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cámaras' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cameras' FROM SUBCATEGORY);

-- Monitores y pantallas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Monitores y pantallas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Monitors and screens' FROM SUBCATEGORY);

-- Seguridad y vigilancia
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Seguridad y vigilancia' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Security and surveillance' FROM SUBCATEGORY);

-- GPS
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'GPS' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'GPS' FROM SUBCATEGORY);

-- Impresoras y fotocopiadoras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrónica, video y audio');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Impresoras y fotocopiadoras' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Printers and photocopiers' FROM SUBCATEGORY);

-- Subcategorías de --> Celulares, tablets, telefonía y computación ------------------------------------------------------------------------------------------------------------------------------------------------

-- Accesorios para celulares
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Accesorios para celulares' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cellphone accessories' FROM SUBCATEGORY);

-- Celulares y smartphones
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Celulares y smartphones' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cellphones and smartphones' FROM SUBCATEGORY);

-- Teléfonos fijos e inalámbricos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Teléfonos fijos e inalámbricos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Landlines and wireless phones' FROM SUBCATEGORY);

-- Tablets y accesorios
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Tablets y accesorios' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Tablets and accessories' FROM SUBCATEGORY);

-- Accesorios y componentes de PC
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Accesorios y componentes de PC' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'PC accessories and components' FROM SUBCATEGORY);

-- Periféricos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Periféricos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Peripherals' FROM SUBCATEGORY);

-- Computadoras y servidores
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Computadoras y servidores' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Computers and servers' FROM SUBCATEGORY);

-- Notebooks o Netbooks
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Notebooks y Netbooks' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Notebooks and Netbooks' FROM SUBCATEGORY);

-- Software
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Software' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Software' FROM SUBCATEGORY);

-- Pendrives
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Celulares, tablets, telefonía y computación');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Pendrives' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Flash drive' FROM SUBCATEGORY);

-- Subcategorías de --> Consolas y videojuegos ------------------------------------------------------------------------------------------------------------------------------------------------

-- Juegos de PC
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Consolas y videojuegos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Juegos de PC' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'PC games' FROM SUBCATEGORY);

-- Playstation
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Consolas y videojuegos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Playstation' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Playstation' FROM SUBCATEGORY);

-- Xbox
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Consolas y videojuegos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Xbox' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Xbox' FROM SUBCATEGORY);

-- Juegos de otras consolas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Consolas y videojuegos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Juegos de otras consolas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Games of other consoles' FROM SUBCATEGORY);

-- Consolas antiguas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Consolas y videojuegos');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Consolas antiguas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Old consoles' FROM SUBCATEGORY);

-- Subcategorías de --> Electrodomésticos grandes ------------------------------------------------------------------------------------------------------------------------------------------------

-- Calefones y termotanques
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Calefones y termotanques' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Boilers and thermotanks' FROM SUBCATEGORY);

-- Calefacción
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Calefacción' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Heating' FROM SUBCATEGORY);

-- Cocinas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cocinas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Kitchens' FROM SUBCATEGORY);

-- Heladeras y freezers
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Heladeras y congeladores' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Refrigerators and freezers' FROM SUBCATEGORY);

-- Microondas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Microondas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Microwave' FROM SUBCATEGORY);

-- Lavavajillas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Lavavajillas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Dishwasher' FROM SUBCATEGORY);

-- Lavarropas y secarropas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos grandes');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Lavarropas y secarropas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Washer and dryer' FROM SUBCATEGORY);

-- Subcategorías de --> Electrodomésticos pequeños ------------------------------------------------------------------------------------------------------------------------------------------------

-- Cafeteras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos pequeños');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cafeteras' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Coffe makers' FROM SUBCATEGORY);

-- Jugueras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos pequeños');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Jugueras ' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Juicer' FROM SUBCATEGORY);

-- Máquinas para pop
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos pequeños');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Máquinas para pop' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Popcorn machines' FROM SUBCATEGORY);

-- Licuadoras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Electrodomésticos pequeños');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Licuadoras' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Blenders' FROM SUBCATEGORY);

-- Subcategorías de --> Hogar, muebles y jardín ------------------------------------------------------------------------------------------------------------------------------------------------

-- Baño
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Baño' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Bathroom' FROM SUBCATEGORY);

-- Cocina y bazar
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cocina y bazar' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Kitchen and bazaar' FROM SUBCATEGORY);

-- Comedor y living
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Comedor y living' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Dining and living room' FROM SUBCATEGORY);

-- Decoración
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Decoración' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Decoration' FROM SUBCATEGORY);

-- Dormitorio
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Dormitorio' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Bedroom' FROM SUBCATEGORY);

-- Jardín y exterior
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Jardín y exterior' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Garden and outdoor' FROM SUBCATEGORY);

-- Iluminación
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Hogar, muebles y jardín');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Iluminación' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Lighting' FROM SUBCATEGORY);

-- Subcategorías de --> Ropa, calzado y accesorios ------------------------------------------------------------------------------------------------------------------------------------------------

-- Bermudas y shorts
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Bermudas y shorts' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Bermuda and shorts' FROM SUBCATEGORY);

-- Busos y canguros
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Busos y canguros' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Sweatshirts' FROM SUBCATEGORY);

-- Camperas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Camperas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Jackets' FROM SUBCATEGORY);

-- Championes y zapatos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Championes y zapatos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Shoes' FROM SUBCATEGORY);

-- Camisas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Camisas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Shirts' FROM SUBCATEGORY);

-- Camisetas y remeras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Camisetas y remeras' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'T-shirts' FROM SUBCATEGORY);

-- Carteras y mochilas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Carteras y mochilas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Handbags and backpacks' FROM SUBCATEGORY);

-- Chalecos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Chalecos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Vests' FROM SUBCATEGORY);

-- Chaquetas y blazers
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Chaquetas y blazers' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Jackets and blazers' FROM SUBCATEGORY);

-- Lentes
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Lentes' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Glasses' FROM SUBCATEGORY);

-- Relojes y joyas
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Relojes y joyas' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Watches and jewellery' FROM SUBCATEGORY);

-- Ropa deportiva
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Ropa deportiva' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Sportswear' FROM SUBCATEGORY);

-- Polleras
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Polleras' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Skirts' FROM SUBCATEGORY);

-- Ropa interior
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Ropa interior' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Underwear' FROM SUBCATEGORY);

-- Pijamas y ropa de dormir
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Pijamas y ropa de dormir' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Pajamas and nightwear' FROM SUBCATEGORY);

-- Trajes de baño
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Trajes de baño' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Bathing suit' FROM SUBCATEGORY);

-- Uniformes
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Uniformes' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Uniforms' FROM SUBCATEGORY);

-- Vestidos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Vestidos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Dresses' FROM SUBCATEGORY);

-- Ropa formal
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Ropa, calzado y accesorios');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Ropa formal' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Formal clothing' FROM SUBCATEGORY);

-- Subcategorías de --> Salud y belleza ------------------------------------------------------------------------------------------------------------------------------------------------

-- Cuidados
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Salud y belleza');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cuidados' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Cares' FROM SUBCATEGORY);

-- Maquillaje
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Salud y belleza');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Maquillaje' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Makeup' FROM SUBCATEGORY);

-- Medicamentos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Salud y belleza');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Medicamentos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Medications' FROM SUBCATEGORY);

-- Perfumes y fragancias
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Salud y belleza');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Perfumes y fragancias' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Perfumes and fragrances' FROM SUBCATEGORY);

-- Vitaminas y complementos
INSERT INTO SUBCATEGORY(ID_CATEGORY)
(SELECT ID_CATEGORY FROM CATEGORY_ES WHERE NAME = 'Salud y belleza');

INSERT INTO SUBCATEGORY_ES(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Vitaminas y complementos' FROM SUBCATEGORY);

INSERT INTO SUBCATEGORY_EN(ID_SUBCATEGORY, NAME)
(SELECT MAX(ID_SUBCATEGORY), 'Vitamins and supplements' FROM SUBCATEGORY);