  CREATE TABLE USERS(
	ID_USER SERIAL PRIMARY KEY NOT NULL,
	FULL_NAME VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL,
	DATE_OF_BIRTH DATE,
	PHONE VARCHAR NOT NULL,
	STATUS INTEGER,
	IMAGE VARCHAR,
	ROL INTEGER,
	DEPARTAMENT VARCHAR,
	CITY VARCHAR,
	STREET VARCHAR,
	NEIGHBORHOOD VARCHAR
 );
 
 CREATE TABLE STORE(
	ID_USER SERIAL PRIMARY KEY NOT NULL,
	RUT VARCHAR NOT NULL,
	SOCIAL_REASON VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER)
 );
 
 CREATE TABLE ADMINS(
	ID_USER SERIAL PRIMARY KEY NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL
 );
 
 CREATE TABLE CATEGORY(
	ID_CATEGORY SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR NOT NULL,
	ICON VARCHAR
 );
 
 CREATE TABLE SUBCATEGORY(
	ID_SUBCATEGORY SERIAL PRIMARY KEY NOT NULL,
	ID_CATEGORY SERIAL NOT NULL,
	NAME VARCHAR NOT NULL,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
 );
 
 CREATE TABLE PRODUCT(
	ID_PRODUCT SERIAL PRIMARY KEY NOT NULL,
	ID_USER SERIAL NOT NULL,
	PRICE INTEGER NOT NULL,
	CURRENCY VARCHAR NOT NULL,
	DATE_OF_CREATION TIMESTAMP,
	DESCRIPTION	VARCHAR NOT NULL,
	CATEGORY SERIAL NOT NULL,
	SUBCATEGORY SERIAL NOT NULL,
	NAME VARCHAR NOT NULL,
	STOCK INTEGER,
	WARRANTY VARCHAR,
	STATUS INTEGER,
	IS_NEW INTEGER,
	
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY(SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );

CREATE TABLE PRODUCT_IMG(
	ID_PRODUCT SERIAL NOT NULL,
	IMAGE VARCHAR NOT NULL,
	ID_IMG SERIAL NOT NULL,

	PRIMARY KEY(ID_PRODUCT, ID_IMG),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);
 
 CREATE TABLE PRODUCT_COMMENT(
	ID_COMMENT SERIAL PRIMARY KEY NOT NULL,
	ID_USER	SERIAL NOT NULL,
	COMMENT_TEXT VARCHAR NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	COMMENT_DATE TIMESTAMP,
	
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE PRODUCT_RATING(
	ID_USER	SERIAL NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	TITLE VARCHAR,
	RATING_NUMBER INTEGER,
	DESCRIPTION	VARCHAR,
	
	PRIMARY KEY(ID_USER, ID_PRODUCT),
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE FAVOURITE(
	ID_USER	SERIAL NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	
	PRIMARY KEY(ID_USER, ID_PRODUCT),
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE HISTORY(
	ID_USER	SERIAL NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	DATE_OF_VISIT TIMESTAMP NOT NULL,
	
	 PRIMARY KEY(ID_USER, ID_PRODUCT),
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
 );
 
 CREATE TABLE COMMENT_ANSWER(
	ID_ANSWER SERIAL PRIMARY KEY NOT NULL,
	ID_USER	SERIAL,
	ANSWER_TEXT	VARCHAR,
	ID_PRODUCT SERIAL,
	ID_COMMENT SERIAL,
	ANSWER_DATE TIMESTAMP,
	
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
	FOREIGN KEY(ID_COMMENT) REFERENCES PRODUCT_COMMENT(ID_COMMENT)
 );
 
 CREATE TABLE SELL(
	ID_SELL SERIAL PRIMARY KEY NOT NULL,
	ID_SELLER_USER SERIAL NOT NULL,
	ID_BUYER_USER SERIAL NOT NULL,
	ID_PRODUCT SERIAL NOT NULL,
	SELL_DATE DATE,
	
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
	FOREIGN KEY(ID_SELLER_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_BUYER_USER) REFERENCES USERS(ID_USER)
);
 
 CREATE TABLE CATEGORY_BRAND(
	ID_CATEGORY SERIAL PRIMARY KEY NOT NULL,
	BRAND VARCHAR,
	
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
 );
 
  CREATE TABLE SUBCATEGORY_BRAND(
	ID_SUBCATEGORY SERIAL PRIMARY KEY NOT NULL,
	BRAND VARCHAR,
	
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );
 
 CREATE TYPE FILTER_TYPE AS ENUM ('NUMERIC_RANGE', 'BOOLEAN', 'OPTIONS_LIST','DATE_RANGE','SELECTIONABLE_LIST', 'INPUT');
 
  CREATE TABLE FILTER(
	ID_FILTER SERIAL PRIMARY KEY NOT NULL,
	IS_GENERIC INTEGER,
	FILTER_NAME VARCHAR NOT NULL,
	FILTER_TYPE FILTER_TYPE,
	ID_CATEGORY SERIAL,
	ID_SUBCATEGORY SERIAL,
	TABLE_NAME VARCHAR,
	COLUMN_NAME VARCHAR,

	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY)
 );
 
 CREATE TABLE CATEGORY_FILTER(
	ID_CATEGORY SERIAL NOT NULL,
	ID_FILTER SERIAL NOT NULL,
	
	PRIMARY KEY(ID_CATEGORY, ID_FILTER),
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
 );
 
 CREATE TABLE SUBCATEGORY_FILTER(
	ID_SUBCATEGORY SERIAL NOT NULL,
	ID_FILTER SERIAL NOT NULL,
	
	PRIMARY KEY(ID_SUBCATEGORY, ID_FILTER),
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY),
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
 );
 
 CREATE TABLE NOTIFICATION_GENERIC(
	ID_NOTIFICATION SERIAL PRIMARY KEY NOT NULL,
	MESSAGE VARCHAR NOT NULL,
	ID_USER SERIAL NOT NULL,
	NOTIFICATION_DATE TIMESTAMP NOT NULL,
	
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER)
);

 CREATE TABLE NOTIFICATION_COMMENT(
	ID_NOTIFICATION SERIAL PRIMARY KEY NOT NULL,
	ID_COMMENT SERIAL NOT NULL,
	
	FOREIGN KEY(ID_COMMENT) REFERENCES PRODUCT_COMMENT(ID_COMMENT)
);

 CREATE TABLE NOTIFICATION_ANSWER(
	ID_NOTIFICATION SERIAL PRIMARY KEY NOT NULL,
	ID_ANSWER SERIAL NOT NULL,
	
	FOREIGN KEY(ID_ANSWER) REFERENCES COMMENT_ANSWER(ID_ANSWER)
);

CREATE TABLE FILTER_OPTION(
	ID_FILTER SERIAL NOT NULL,
	OPTION_VALUE VARCHAR,

	PRIMARY KEY(ID_FILTER, OPTION_VALUE),
	FOREIGN KEY(ID_FILTER) REFERENCES FILTER(ID_FILTER)
);

CREATE TABLE CODE_CONFIRM(
	ID_USER SERIAL NOT NULL PRIMARY KEY,
	CODE INTEGER NOT NULL,
	
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER)
);

CREATE TABLE PUBLICATION_REPORT(
	ID_PRODUCT SERIAL NOT NULL,
	DESCRIPTION VARCHAR,
	ID_USER SERIAL NOT NULL,

	PRIMARY KEY(ID_PRODUCT, ID_USER),
	FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);