CREATE TABLE VEHICLE(
    ID_CATEGORY SERIAL NOT NULL,
    ID_PRODUCT SERIAL NOT NULL,
    YEAR INTEGER NOT NULL,
    KILOMETERS INTEGER NOT NULL,

    PRIMARY KEY(ID_PRODUCT),
	FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

-- Filtros para VEHICLE

-- Año
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Año', 'INPUT', ID_CATEGORY, 0 FROM CATEGORY WHERE NAME = 'Vehículos');

-- Kilómetros
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Kilómetros', 'INPUT', ID_CATEGORY, 0 FROM CATEGORY WHERE NAME = 'Vehículos');

CREATE TABLE CAR(
    ID_SUBCATEGORY SERIAL NOT NULL,
    ID_PRODUCT SERIAL NOT NULL,
    BRAND VARCHAR,
    MODEL VARCHAR,
    ENGINE VARCHAR,
    FUEL_TYPE VARCHAR,
    DIRECTION VARCHAR,
    ABS BOOLEAN NOT NULL,
    AIRBAG BOOLEAN NOT NULL,
    AIR_CONDITIONING BOOLEAN NOT NULL,
    
    PRIMARY KEY(ID_PRODUCT),
	FOREIGN KEY(ID_SUBCATEGORY) REFERENCES SUBCATEGORY(ID_SUBCATEGORY),
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

-- Filtros para CAR

-- Marca
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Marca', 'SELECTIONABLE_LIST', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Modelo
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Modelo', 'SELECTIONABLE_LIST', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Motor
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Motor', 'INPUT', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Tipo de combustible
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Tipo de combustible', 'SELECTIONABLE_LIST', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Tipo de dirección
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Tipo de dirección', 'SELECTIONABLE_LIST', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Frenos ABS
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Frenos ABS', 'BOOLEAN', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Aire acondicionado
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Aire acondicionado', 'BOOLEAN', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');

-- Airbag
INSERT INTO FILTER(IS_GENERIC, FILTER_NAME, FILTER_TYPE, ID_CATEGORY, ID_SUBCATEGORY)
(SELECT 0, 'Airbag', 'BOOLEAN', 0, ID_SUBCATEGORY FROM SUBCATEGORY WHERE NAME = 'Autos');


INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Fiat' FROM FILTER WHERE FILTER_NAME = 'Marca');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Citroen' FROM FILTER WHERE FILTER_NAME = 'Marca');


INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Nafta' FROM FILTER WHERE FILTER_NAME = 'Tipo de combustible');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Gasoil' FROM FILTER WHERE FILTER_NAME = 'Tipo de combustible');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Hidráulica' FROM FILTER WHERE FILTER_NAME = 'Tipo de dirección');

INSERT INTO FILTER_OPTION(ID_FILTER, OPTION_VALUE)
(SELECT ID_FILTER, 'Asistida' FROM FILTER WHERE FILTER_NAME = 'Tipo de dirección');

UPDATE FILTER SET TABLE_NAME = 'VEHICLE' WHERE ID_CATEGORY = 1;
UPDATE FILTER SET TABLE_NAME = 'CAR' WHERE ID_SUBCATEGORY = 1;

update filter set COLUMN_NAME = 'BRAND' WHERE FILTER_NAME = 'Marca';
update filter set COLUMN_NAME = 'MODEL' WHERE FILTER_NAME = 'Modelo';
update filter set COLUMN_NAME = 'ENGINE' WHERE FILTER_NAME = 'Motor';
update filter set COLUMN_NAME = 'FUEL_TYPE' WHERE FILTER_NAME = 'Tipo de combustible';
update filter set COLUMN_NAME = 'DIRECTION' WHERE FILTER_NAME = 'Tipo de dirección';
update filter set COLUMN_NAME = 'DIRECTION' WHERE FILTER_NAME = 'Tipo de dirección';
update filter set COLUMN_NAME = 'ABS' WHERE FILTER_NAME = 'Frenos ABS';
update filter set COLUMN_NAME = 'AIRBAG' WHERE FILTER_NAME = 'Airbag';
update filter set COLUMN_NAME = 'AIR_CONDITIONING' WHERE FILTER_NAME = 'Aire acondicionado';

update filter set COLUMN_NAME = 'YEAR' WHERE FILTER_NAME = 'Año';
update filter set COLUMN_NAME = 'KILOMETERS' WHERE FILTER_NAME = 'Kilómetros';