SELECT SCATES.NAME AS SpanishName,
SCATEN.NAME AS EnglishName,
SCAT.ID_SUBCATEGORY AS IdSubcategory,
SCAT.ID_CATEGORY AS IdCategory
from SUBCATEGORY SCAT INNER JOIN SUBCATEGORY_ES SCATES
	ON SCAT.ID_SUBCATEGORY = SCATES.ID_SUBCATEGORY
INNER JOIN SUBCATEGORY_EN SCATEN
	ON SCAT.ID_SUBCATEGORY = SCATEN.ID_SUBCATEGORY